name: Build Mac

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build and publish Mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish-mac
